import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navegation from './components/Home/Navegation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio - Nahuel Gomez',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navegation/>
        {children}
        </body>
    </html>
  )
}
